#NAME: Yuanping Song
#EMAIL: yuanping.song@outlook.com
#ID: 

CC=gcc
CFLAGS =-Wall -Wextra -std=c11

lab1a: 
	$(CC) $(CFLAGS) -o lab1a lab1a.c
clean: lab1a
	rm lab1a lab1a-xxxxxxxxx.tar.gz
dist:
	tar -czf lab1a-xxxxxxxxx.tar.gz Makefile README lab1a.c
